version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "233895708333.dkr.ecr.us-east-1.amazonaws.com"
          repo: "orr-dev-repo"
          region: "us-east-1"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          family: "td-testing-reporting-api"
          cluster-name: "cluster-test-reporting-api"
          container-image-name-updates: 'container=container-orr-api-service,tag=${CIRCLE_SHA1}'  
